# Site settings
title:       Joshua Sierles
email:       joshua@diluvia.net
author:      Joshua Sierles
description: "Joshua Sierles' personal site. Posts about Ruby, Rails, React Native, flamenco and Spain."
baseurl:     ""
url:         "http://joshua.si"

# Google analytics
google_analytics: UA-35360701-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: joshuasierles

# Social icons
show_social_icons: true
github_username: jsierles
stackoverflow_id:
twitter_username: jsierles
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
